name: DataMiner CICD Update Catalog Details

# Controls when the workflow will run
on:
  # push:
  #   branches:
  #     - main
  #     - master

  ## If you wish to only trigger on ReadMe changes. 
  ## Consider: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  Catalog:
    uses: SkylineCommunications/_ReusableWorkflows/.github/workflows/Update Catalog Details Workflow.yml@main
    secrets:
      # The API-key: generated in the DCP Admin app (https://admin.dataminer.services/) as authentication for a certain DataMiner Organization or Agent.
      api-key: ${{ secrets.DATAMINER_TOKEN }}